//
//  PentoSolutions.swift
//  PentoFace WatchKit Extension
//
//  Created by Nicholaos Mouzourakis on 2020-04-01.
//  Copyright © 2020 NEVUM X. All rights reserved.
//

enum Pentomino : String, CaseIterable {
	case PentominoX, PentominoN, PentominoI, PentominoU, PentominoV, PentominoW, PentominoT, PentominoF, PentominoL, PentominoP, PentominoY, PentominoZ
}

struct PentominoInstance {
	let pentomino: Pentomino
	let flipped: Bool
	let rotations: UInt8
	let rowOffset: UInt8
	let columnOffset: UInt8
}

let solutions =
[
	[
		[
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 2, rowOffset: 1, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 2, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 2, rowOffset: 1, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 0, rowOffset: 3, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 2, rowOffset: 5, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 1, rowOffset: 8, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 1, rowOffset: 6, columnOffset: 3),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 2, rowOffset: 1, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 2, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 2, rowOffset: 1, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 2, rowOffset: 5, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 1, rowOffset: 8, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 1, rowOffset: 6, columnOffset: 3),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 1, rowOffset: 1, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 0, rowOffset: 2, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 5, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 2, rowOffset: 3, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 0, rowOffset: 5, columnOffset: 4),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 1, rowOffset: 1, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 0, rowOffset: 2, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 5, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 2, rowOffset: 3, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 0, rowOffset: 5, columnOffset: 4),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 3, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 0, rowOffset: 2, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 0, rowOffset: 5, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 1, rowOffset: 7, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 2, rowOffset: 3, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 0, rowOffset: 5, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 3, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 0, rowOffset: 2, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 0, rowOffset: 5, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 1, rowOffset: 7, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 2, rowOffset: 3, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 0, rowOffset: 5, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 2, rowOffset: 1, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 2, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 2, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 2, rowOffset: 5, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 3, rowOffset: 8, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 3, rowOffset: 6, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 2, rowOffset: 1, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 2, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 2, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 0, rowOffset: 3, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 2, rowOffset: 5, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 3, rowOffset: 8, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 3, rowOffset: 6, columnOffset: 0),
		],
	],
	[
		[
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 1, rowOffset: 8, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 1, rowOffset: 8, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 2, rowOffset: 6, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 0, rowOffset: 3, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 2, rowOffset: 1, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 0, rowOffset: 0, columnOffset: 1),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 1, rowOffset: 8, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 1, rowOffset: 8, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 2, rowOffset: 6, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 2, rowOffset: 1, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 0, rowOffset: 0, columnOffset: 1),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 1, rowOffset: 9, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 1, rowOffset: 7, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 3, rowOffset: 6, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 0, rowOffset: 3, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 2, rowOffset: 1, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 0, rowOffset: 0, columnOffset: 1),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 1, rowOffset: 9, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 1, rowOffset: 7, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 3, rowOffset: 6, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 2, rowOffset: 1, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 0, rowOffset: 0, columnOffset: 1),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 1, rowOffset: 9, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 1, rowOffset: 7, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 3, rowOffset: 6, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 2, rowOffset: 1, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 0, rowOffset: 0, columnOffset: 2),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 1, rowOffset: 9, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 1, rowOffset: 7, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 3, rowOffset: 6, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 0, rowOffset: 2, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 1),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: true, rotations: 1, rowOffset: 7, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 1, rowOffset: 9, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 0, rowOffset: 6, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 0, rowOffset: 2, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 1),
		],
	],
	[
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 0, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 3, rowOffset: 8, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 1, rowOffset: 7, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 1, rowOffset: 7, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 1, rowOffset: 5, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoX, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 2, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 2, rowOffset: 0, columnOffset: 2),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 3, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 1, rowOffset: 1, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoX, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 1, rowOffset: 5, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 3, rowOffset: 8, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 1, rowOffset: 7, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 1, rowOffset: 7, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 3, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: true, rotations: 0, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 2, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoX, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 1, rowOffset: 5, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 3, rowOffset: 8, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 1, rowOffset: 7, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 1, rowOffset: 7, columnOffset: 0),
		],
	],
	[
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 0, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 1, rowOffset: 8, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 2, rowOffset: 6, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 0, rowOffset: 1, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 1, rowOffset: 4, columnOffset: 2),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 0, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 1, rowOffset: 8, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 0, rowOffset: 1, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 1, rowOffset: 4, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 2, rowOffset: 6, columnOffset: 4),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 0, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 1, rowOffset: 8, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 0, rowOffset: 1, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 2, rowOffset: 5, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: true, rotations: 1, rowOffset: 3, columnOffset: 2),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 3, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 0, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 1, rowOffset: 8, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 2, rowOffset: 5, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: true, rotations: 1, rowOffset: 3, columnOffset: 2),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 3, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 1, rowOffset: 8, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 0, rowOffset: 1, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 1, rowOffset: 4, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 2, rowOffset: 6, columnOffset: 4),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 3, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 1, rowOffset: 8, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 0, rowOffset: 1, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 2, rowOffset: 5, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: true, rotations: 1, rowOffset: 3, columnOffset: 2),
		],
	],
	[
		[
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 6, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 1, rowOffset: 1, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 2, rowOffset: 2, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 1, rowOffset: 4, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 6, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 1, rowOffset: 1, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 2, rowOffset: 2, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 1, rowOffset: 4, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 1, rowOffset: 3, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 6, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 2, rowOffset: 1, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 3, rowOffset: 4, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 2, rowOffset: 2, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 6, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 2, rowOffset: 1, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 3, rowOffset: 4, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 2, rowOffset: 2, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 6, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 2, rowOffset: 1, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 2, rowOffset: 2, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 3, rowOffset: 4, columnOffset: 1),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 6, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 2, rowOffset: 1, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 2, rowOffset: 2, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 3, rowOffset: 4, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 6, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 0, rowOffset: 2, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 1, rowOffset: 4, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 3, rowOffset: 3, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 0, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 2),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 6, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 0, rowOffset: 2, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 1, rowOffset: 4, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 1, rowOffset: 3, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 0, rowOffset: 1, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 2),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 6, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 0, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 2, rowOffset: 2, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 1, rowOffset: 3, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 6, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 0, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 2, rowOffset: 2, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 1, rowOffset: 4, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 1, rowOffset: 3, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 6, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 0, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 2, rowOffset: 2, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 1, rowOffset: 3, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 6, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 3, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 2, rowOffset: 2, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 3, rowOffset: 4, columnOffset: 1),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 6, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 3, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 2, rowOffset: 2, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 3, rowOffset: 4, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 2, rowOffset: 7, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 0, rowOffset: 1, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 1, rowOffset: 5, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 1, rowOffset: 3, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 2, rowOffset: 7, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 0, rowOffset: 2, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 1, rowOffset: 4, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 1, rowOffset: 3, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 2),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 2, rowOffset: 7, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 1, rowOffset: 3, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 2, rowOffset: 7, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 0, rowOffset: 5, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 0, rowOffset: 1, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 1, rowOffset: 2, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 2, rowOffset: 7, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 0, rowOffset: 5, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 0, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 3, rowOffset: 3, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 2, rowOffset: 7, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 0, rowOffset: 5, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 2, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 1, rowOffset: 4, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 1, rowOffset: 3, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 2, rowOffset: 7, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 0, rowOffset: 4, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 2, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 1, rowOffset: 3, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 0, rowOffset: 6, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 2, rowOffset: 2, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 0, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 1, rowOffset: 3, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 0, rowOffset: 6, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 2, rowOffset: 2, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 0, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 1, rowOffset: 3, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 2, rowOffset: 7, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 0, rowOffset: 4, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 2, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 1, rowOffset: 3, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 2, rowOffset: 7, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 1, rowOffset: 4, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 2, rowOffset: 1, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 2, rowOffset: 1, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 2, rowOffset: 7, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 2, rowOffset: 3, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 1, rowOffset: 4, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 2, rowOffset: 2, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 2, rowOffset: 1, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 3),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 2, rowOffset: 7, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 1, rowOffset: 5, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 0, rowOffset: 1, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 1, rowOffset: 2, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 2, rowOffset: 7, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 1, rowOffset: 5, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 0, rowOffset: 1, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 0, rowOffset: 2, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 2, rowOffset: 7, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 0, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 1, rowOffset: 5, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 1, rowOffset: 3, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 2, rowOffset: 7, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 0, rowOffset: 2, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 1, rowOffset: 4, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 3, rowOffset: 3, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 2),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 2, rowOffset: 7, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 1, rowOffset: 3, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 0),
		],
	],
	[
		[
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 3, rowOffset: 8, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: true, rotations: 0, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 0, rowOffset: 2, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 1, rowOffset: 3, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 2, rowOffset: 4, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 2, rowOffset: 6, columnOffset: 3),
		],
	],
	[
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 3, rowOffset: 3, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 0, rowOffset: 6, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 3, rowOffset: 8, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 3, rowOffset: 4, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 0, rowOffset: 6, columnOffset: 4),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 0, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 1, rowOffset: 4, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 2, rowOffset: 5, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 2, rowOffset: 5, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 0, rowOffset: 7, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 1, rowOffset: 7, columnOffset: 2),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 0, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 1, rowOffset: 4, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 2, rowOffset: 5, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 2, rowOffset: 5, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 2),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 0, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: true, rotations: 1, rowOffset: 4, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 2, rowOffset: 6, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 2, rowOffset: 4, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 1, rowOffset: 8, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 2, rowOffset: 6, columnOffset: 3),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 0, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 2, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 2, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 2, rowOffset: 6, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 1, rowOffset: 4, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 1, rowOffset: 8, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 2, rowOffset: 5, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 2, rowOffset: 6, columnOffset: 3),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 0, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 2, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 2, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 2, rowOffset: 6, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 1, rowOffset: 4, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 1, rowOffset: 8, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 0, rowOffset: 5, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 3, rowOffset: 6, columnOffset: 3),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 0, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 2, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 2, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 0, rowOffset: 5, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 1, rowOffset: 4, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 2, rowOffset: 5, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 1, rowOffset: 7, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 1, rowOffset: 8, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 0, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 1, rowOffset: 3, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 2, rowOffset: 5, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 2, rowOffset: 4, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 1, rowOffset: 8, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 2, rowOffset: 6, columnOffset: 3),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 0, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 0, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 1, rowOffset: 8, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 1, rowOffset: 5, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 3, rowOffset: 4, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 2, rowOffset: 5, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 1, rowOffset: 7, columnOffset: 2),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 3, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 1, rowOffset: 8, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 1, rowOffset: 5, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 3, rowOffset: 4, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 2, rowOffset: 5, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 1, rowOffset: 7, columnOffset: 2),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: true, rotations: 1, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 3, rowOffset: 3, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 0, rowOffset: 6, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 3, rowOffset: 8, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 3, rowOffset: 4, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 0, rowOffset: 6, columnOffset: 4),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 0, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 3, rowOffset: 3, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 0, rowOffset: 6, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 3, rowOffset: 8, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 3, rowOffset: 4, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 0, rowOffset: 6, columnOffset: 4),
		],
	],
	[
		[
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 2, rowOffset: 1, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoX, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 3, rowOffset: 5, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 2, rowOffset: 7, columnOffset: 1),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 2, rowOffset: 1, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 3, rowOffset: 3, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: true, rotations: 1, rowOffset: 5, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 2, rowOffset: 7, columnOffset: 1),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 0, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoX, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 3, rowOffset: 5, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 2, rowOffset: 7, columnOffset: 1),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 0, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 3, rowOffset: 3, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: true, rotations: 1, rowOffset: 5, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 2, rowOffset: 7, columnOffset: 1),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 6, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 2, rowOffset: 5, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 3, rowOffset: 3, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: true, rotations: 0, rowOffset: 1, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 3),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 6, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 2, rowOffset: 3, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: true, rotations: 0, rowOffset: 1, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 3),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 6, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 2, rowOffset: 5, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoX, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: true, rotations: 0, rowOffset: 1, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 3),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 0, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoX, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 3, rowOffset: 5, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 2, rowOffset: 7, columnOffset: 1),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 0, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 3, rowOffset: 3, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: true, rotations: 1, rowOffset: 5, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 2, rowOffset: 7, columnOffset: 1),
		],
	],
	[
		[
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 2, rowOffset: 2, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 1, rowOffset: 1, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 1, rowOffset: 3, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: true, rotations: 1, rowOffset: 4, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 0, rowOffset: 5, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 1, rowOffset: 8, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 2, rowOffset: 6, columnOffset: 4),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 3, rowOffset: 3, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 2, rowOffset: 6, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 0, rowOffset: 7, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 3, rowOffset: 8, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 0, rowOffset: 5, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 1, rowOffset: 4, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 2, rowOffset: 2, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 3, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 3),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 3, rowOffset: 3, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 2, rowOffset: 6, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 0, rowOffset: 7, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 3, rowOffset: 8, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 0, rowOffset: 5, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 1, rowOffset: 4, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 2, rowOffset: 2, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 3, rowOffset: 1, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 3, rowOffset: 3, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 2, rowOffset: 6, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 0, rowOffset: 7, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 1, rowOffset: 7, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 5, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 1, rowOffset: 4, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 2, rowOffset: 2, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 2, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 3),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 3, rowOffset: 3, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 2, rowOffset: 6, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 5, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 1, rowOffset: 4, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 2, rowOffset: 2, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 2, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 1, rowOffset: 0, columnOffset: 3),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 3, rowOffset: 2, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 1, rowOffset: 1, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 1, rowOffset: 3, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: true, rotations: 1, rowOffset: 4, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 0, rowOffset: 5, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 1, rowOffset: 8, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 2, rowOffset: 6, columnOffset: 4),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 3, rowOffset: 2, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 1, rowOffset: 3, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: true, rotations: 1, rowOffset: 4, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 5, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 0, rowOffset: 7, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 2, rowOffset: 6, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 1, rowOffset: 7, columnOffset: 2),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 3, rowOffset: 2, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoU, flipped: false, rotations: 1, rowOffset: 3, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: true, rotations: 1, rowOffset: 4, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 5, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 2, rowOffset: 6, columnOffset: 4),
		],
	],
	[
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 0, rowOffset: 7, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 0, rowOffset: 6, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 1, rowOffset: 4, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 2, rowOffset: 1, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 1, rowOffset: 4, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 2, rowOffset: 1, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 2, rowOffset: 7, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 2, rowOffset: 5, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 3, rowOffset: 4, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 0, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 2),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 2, rowOffset: 7, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 2, rowOffset: 5, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 3, rowOffset: 4, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 0, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 2, rowOffset: 0, columnOffset: 2),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 2, rowOffset: 7, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 4, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 2, rowOffset: 5, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: true, rotations: 1, rowOffset: 3, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 0, rowOffset: 1, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 0, rowOffset: 2, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 2, rowOffset: 7, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 5, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 3, rowOffset: 4, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 1, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 2, rowOffset: 2, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 2, rowOffset: 7, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 5, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 3, rowOffset: 4, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 0, rowOffset: 2, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 2, rowOffset: 7, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 0, rowOffset: 5, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 3, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 0, rowOffset: 2, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 3, rowOffset: 4, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 0, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 1),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 2, rowOffset: 7, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 2, rowOffset: 6, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 1, rowOffset: 4, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 0, rowOffset: 1, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 0, rowOffset: 2, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: true, rotations: 2, rowOffset: 7, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 2, rowOffset: 6, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 2, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 3, rowOffset: 2, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 1, rowOffset: 4, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 0, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 1),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoW, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: false, rotations: 1, rowOffset: 8, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 1, rowOffset: 6, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 2, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 3, rowOffset: 2, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: true, rotations: 1, rowOffset: 4, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 0, rowOffset: 1, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 3, rowOffset: 0, columnOffset: 1),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: true, rotations: 3, rowOffset: 8, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: true, rotations: 1, rowOffset: 6, columnOffset: 3),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 1, rowOffset: 4, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 2, rowOffset: 1, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 1, rowOffset: 4, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 2, rowOffset: 1, columnOffset: 0),
		],
		[
			PentominoInstance(pentomino: Pentomino.PentominoF, flipped: false, rotations: 3, rowOffset: 7, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoZ, flipped: false, rotations: 0, rowOffset: 7, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoN, flipped: false, rotations: 0, rowOffset: 6, columnOffset: 4),
			PentominoInstance(pentomino: Pentomino.PentominoT, flipped: false, rotations: 1, rowOffset: 4, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoI, flipped: false, rotations: 0, rowOffset: 1, columnOffset: 5),
			PentominoInstance(pentomino: Pentomino.PentominoV, flipped: false, rotations: 2, rowOffset: 1, columnOffset: 2),
			PentominoInstance(pentomino: Pentomino.PentominoL, flipped: false, rotations: 1, rowOffset: 0, columnOffset: 1),
			PentominoInstance(pentomino: Pentomino.PentominoY, flipped: true, rotations: 1, rowOffset: 4, columnOffset: 0),
			PentominoInstance(pentomino: Pentomino.PentominoP, flipped: true, rotations: 2, rowOffset: 1, columnOffset: 0),
		],
	],
]
